cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - node_modules/

# test_e2e:
#   image: cypress/browsers:chrome67
#   stage: test
#   script:
#     - npm i
#     - npm run test:e2e -- --headless --record --key b2a22185-8eeb-4f0e-9b21-2d61f769d8c7
#   only:
#     - master

test:build:
  image: node:latest
  stage: test
  script:
    - npm i
    - npm run build

# pages:
#   image: node:latest
#   stage: deploy
#   script:
#     - npm i
#     - npm run build
#     - mv public public-vue
#     - mv dist public
#   artifacts:
#     paths:
#       - public
#   only:
#     - master
